name: connecteo
description: A plugin that wraps connectivity_plus and adds some additionnal data connection checks.
version: 1.0.0
repository: https://github.com/Iteo/connecteo
issue_tracker: https://github.com/Iteo/connecteo/issues
homepage: https://github.com/Iteo/connecteo
documentation: https://github.com/Iteo/connecteo/blob/master/README.md

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  connectivity_plus: ^3.0.2
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  linteo: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.16.0
