name: connecteo
description: A plugin that wraps connectivity_plus and adds some additional data connection checks.
version: 3.0.0
repository: https://github.com/Iteo/connecteo
issue_tracker: https://github.com/Iteo/connecteo/issues
homepage: https://github.com/Iteo/connecteo
documentation: https://github.com/Iteo/connecteo/blob/master/README.md

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  connectivity_plus: ^6.0.1
  flutter:
    sdk: flutter
  http: ^1.1.2
  rxdart: ^0.27.7

dev_dependencies:
  linteo: ^1.1.0
  mocktail: ^1.0.2
  test: ^1.25.0
