name: connecteo
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  connectivity_plus: ^3.0.2
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0
